//! T-P2-005 acceptance, run against a real ffmpeg and a real GPU device.
//!
//! The unit tests in `hwaccel_plan` prove the *arguments* are coherent. These
//! prove ffmpeg *accepts* them, which is a different claim: `scale_vaapi` looks
//! right in a string and still fails if the driver is not what the filter wants.
//!
//! This machine has `/dev/dri/renderD128` (a real render node) and a build of
//! ffmpeg that lists `vaapi`, so a VA-API plan can actually be attempted here.
//! When there is no device the hardware cases skip *and say so*; the software
//! cases always run, so the suite is never silently empty.

use std::path::Path;
use std::process::Command;

use commons_media::hwaccel::{detect, Accel, HwAccelConfig};
use commons_media::hwaccel_plan::{AccelPlan, Planner, SourceKind};
use commons_media::probe::MediaInfo;
use commons_media::thumbs::{Generator, Kind};

/// A generator pointed at the real ffmpeg, with a given plan.
///
/// `with_binaries` is an associated function that builds its own unlimited
/// budget, so the helper takes only the plan. Writing that construction out at
/// every call site is how a test ends up asserting against a generator that
/// was never pointed at anything.
fn generator_with(plan: AccelPlan) -> Generator {
    Generator::with_binaries(ffmpeg(), "ffprobe").with_plan(plan)
}

fn ffmpeg() -> std::path::PathBuf {
    // The same binary the rest of the test suite uses.
    std::env::var("COMMONS_FFMPEG")
        .map(Into::into)
        .unwrap_or_else(|_| "ffmpeg".into())
}

fn skip_without(reason: &str) {
    eprintln!("SKIPPED: {reason}");
}

fn has_hardware() -> bool {
    let status = detect(Path::new(&ffmpeg()), &HwAccelConfig::default());
    status.available.iter().any(|a| a == "vaapi" || a == "qsv")
}

/// The plan this machine would actually use for a video.
fn hw_plan() -> AccelPlan {
    Planner::detect(Path::new(&ffmpeg()), &HwAccelConfig::default())
        .plan_for_source(SourceKind::Video)
}

/// A real short H.264 video, generated by ffmpeg rather than committed, so the
/// decode path is genuinely exercised.
fn make_video(dir: &Path, seconds: u32) -> std::path::PathBuf {
    let out = dir.join("source.mp4");
    let status = Command::new(ffmpeg())
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc=size=320x240:rate=10:duration={seconds}"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            out.to_str().unwrap(),
        ])
        .status();
    assert!(
        status.map(|s| s.success()).unwrap_or(false),
        "could not build a test video"
    );
    out
}

fn info(duration_ms: u64) -> MediaInfo {
    MediaInfo {
        duration_ms,
        ..Default::default()
    }
}

// ============================================================
// The plan reaches ffmpeg
// ============================================================

/// **Accept:** a software plan produces the artifact, and the flags are exactly
/// what the pipeline used before acceleration existed.
///
/// "Exactly" matters: if the software path drifted while acceleration was being
/// added, every existing thumbnail would change and the regression would be
/// blamed on ffmpeg.
#[test]
fn a_software_plan_produces_the_artifact_unchanged() {
    let dir = tempfile::tempdir().unwrap();
    let source = make_video(dir.path(), 1);
    let out = dir.path().join("thumb.webp");

    let g = generator_with(AccelPlan::Software);
    assert_eq!(
        *g.plan(),
        AccelPlan::Software,
        "the default must be software"
    );
    let result = g.generate(&source, &out, Kind::Thumbnail { width: 120 }, &info(1000));
    assert!(
        matches!(result, commons_media::thumbs::Generated::Wrote(_)),
        "{result:?}"
    );
    assert!(out.exists());
    let bytes = std::fs::metadata(&out).unwrap().len();
    assert!(bytes > 0, "wrote an empty file");
    // It really is a WebP: `RIFF`....`WEBP`.
    let head = std::fs::read(&out).unwrap();
    assert_eq!(&head[0..4], b"RIFF");
    assert_eq!(&head[8..12], b"WEBP");
}

/// The same file from the software and hardware plans must both be valid
/// WebP, and the software one must be reproducible.
///
/// This is the alpha guarantee: `-pix_fmt yuva420p` has to survive the encoder
/// being sourced from a plan instead of a literal.
#[test]
fn both_plans_produce_the_same_format() {
    let dir = tempfile::tempdir().unwrap();
    let source = make_video(dir.path(), 1);
    let media = info(1000);

    let gen = || generator_with(AccelPlan::Software);

    let sw_out = dir.path().join("sw.webp");
    let a = gen().with_plan(AccelPlan::Software).generate(
        &source,
        &sw_out,
        Kind::Thumbnail { width: 120 },
        &media,
    );
    assert!(
        matches!(a, commons_media::thumbs::Generated::Wrote(_)),
        "{a:?}"
    );

    if !has_hardware() {
        skip_without("no VA-API or QSV device on this machine");
        return;
    }

    let hw_plan = hw_plan();
    assert!(
        hw_plan.is_hardware(),
        "the device is there; the plan should use it"
    );

    let hw_out = dir.path().join("hw.webp");
    let b = gen().with_plan(hw_plan.clone()).generate(
        &source,
        &hw_out,
        Kind::Thumbnail { width: 120 },
        &media,
    );
    assert!(
        matches!(b, commons_media::thumbs::Generated::Wrote(_)),
        "the hardware plan {hw_plan} was rejected by ffmpeg: {b:?}"
    );
    let head = std::fs::read(&hw_out).unwrap();
    assert_eq!(&head[0..4], b"RIFF", "hardware output is not RIFF");
    assert_eq!(&head[8..12], b"WEBP", "hardware output is not WebP");
}

// ============================================================
// Every kind, every plan
// ============================================================

/// All three kinds, under every plan this machine can build, must all succeed
/// or all fail for a reason that is not "no such filter".
///
/// The failure mode this catches is a plan whose *decode* flags are fine and
/// whose *filter* names a filter ffmpeg does not have -- `scale_nvenc` does not
/// exist, and it would fail on a machine with a perfectly good NVENC card.
#[test]
fn every_kind_works_under_every_usable_plan() {
    let dir = tempfile::tempdir().unwrap();
    let source = make_video(dir.path(), 2);
    let media = info(2000);
    let planner = Planner::detect(Path::new(&ffmpeg()), &HwAccelConfig::default());

    let mut plans = vec![AccelPlan::Software];
    if has_hardware() {
        plans.push(planner.plan_for_source(SourceKind::Video));
    }

    for (i, plan) in plans.iter().enumerate() {
        let gen = generator_with(plan.clone());
        for (j, kind) in [
            Kind::Thumbnail { width: 120 },
            Kind::Marker {
                width: 120,
                at_ms: 500,
            },
            Kind::Sprite {
                width: 100,
                frames: 4,
            },
        ]
        .iter()
        .enumerate()
        {
            let out = dir.path().join(format!("p{i}_k{j}.webp"));
            let result = gen.generate(&source, &out, *kind, &media);
            if let commons_media::thumbs::Generated::Failed(e) = &result {
                let text = format!("{e}");
                assert!(
                    !text.contains("No such filter"),
                    "{plan} rejected {kind:?} with a missing filter: {text}"
                );
                assert!(
                    !text.contains("Impossible to convert"),
                    "{plan} produced an incoherent pixel-format chain for {kind:?}: {text}"
                );
                assert!(
                    !text.contains("Invalid argument"),
                    "{plan} emitted an argument ffmpeg rejected for {kind:?}: {text}"
                );
            }
            assert!(
                matches!(result, commons_media::thumbs::Generated::Wrote(_)),
                "{plan} failed on {kind:?}: {result:?}"
            );
        }
    }
}

/// A sprite under a hardware plan must still have the requested frame count and
/// width. The scale filter is the thing that changed, so the geometry is the
/// thing most likely to be wrong.
#[test]
fn a_hardware_sprite_keeps_the_requested_geometry() {
    let dir = tempfile::tempdir().unwrap();
    let source = make_video(dir.path(), 2);
    let media = info(2000);

    let (frames, width) = (4u32, 100u32);
    let probe = |path: &Path| -> (u32, u32) {
        let out = Command::new("ffprobe")
            .args([
                "-v",
                "error",
                "-select_streams",
                "v:0",
                "-show_entries",
                "stream=width,height",
                "-of",
                "csv=p=0",
                path.to_str().unwrap(),
            ])
            .output()
            .expect("ffprobe");
        let s = String::from_utf8_lossy(&out.stdout);
        let (w, h) = s.trim().split_once(',').expect("dimensions");
        (w.trim().parse().unwrap(), h.trim().parse().unwrap())
    };

    let sw_out = dir.path().join("sw.webp");
    generator_with(AccelPlan::Software).generate(
        &source,
        &sw_out,
        Kind::Sprite { width, frames },
        &media,
    );
    let (sw_w, _) = probe(&sw_out);
    assert_eq!(
        sw_w,
        width * frames,
        "the software sprite is not {frames}x{width}"
    );

    if !has_hardware() {
        skip_without("no VA-API or QSV device on this machine");
        return;
    }
    let hw_plan = hw_plan();
    let hw_out = dir.path().join("hw.webp");
    let result =
        generator_with(hw_plan).generate(&source, &hw_out, Kind::Sprite { width, frames }, &media);
    assert!(
        matches!(result, commons_media::thumbs::Generated::Wrote(_)),
        "{result:?}"
    );
    let (hw_w, _) = probe(&hw_out);
    assert_eq!(
        hw_w,
        width * frames,
        "the hardware sprite is {hw_w} wide, expected {}",
        width * frames
    );
}

// ============================================================
// The status the settings page would show
// ============================================================

/// The status is complete and actionable on this machine, and the plan the
/// settings page would offer actually matches the plan that works.
#[test]
fn the_reported_status_and_the_plan_agree() {
    let status = detect(Path::new(&ffmpeg()), &HwAccelConfig::default());
    status
        .is_actionable()
        .unwrap_or_else(|e| panic!("{e}: {}", status.summary()));

    let planner = Planner::new(status.clone(), &HwAccelConfig::default());
    let plan = planner.plan_for_source(SourceKind::Video);
    if let Some(accel) = plan.accel() {
        assert!(
            status.has(accel),
            "the plan chose {accel} but the status does not list it as available: {}",
            status.summary()
        );
    } else {
        // Declined: there must be a reason, and it must be one of the real
        // causes, not a shrug.
        let reason = planner
            .declined_reason(SourceKind::Video)
            .expect("a declined plan must say why");
        assert!(reason.len() > 20, "{reason:?}");
    }
    // Every accelerator the status knows about is a real one.
    for name in &status.available {
        assert!(Accel::parse(name).is_some(), "{name} is not an Accel");
    }
}

/// Report-only must not change what gets produced, only what the status says.
///
/// #7007: the Docker image runs unprivileged, so the default there is to
/// report rather than to use. If report-only also silently dropped the flags
/// in a way that changed the output, the two would not be interchangeable.
#[test]
fn report_only_reports_and_does_not_accelerate() {
    let dir = tempfile::tempdir().unwrap();
    let source = make_video(dir.path(), 1);
    let media = info(1000);
    let config = HwAccelConfig {
        disabled: vec![],
        report_only: true,
    };
    let planner = Planner::detect(Path::new(&ffmpeg()), &config);
    let plan = planner.plan_for_source(SourceKind::Video);
    assert_eq!(
        plan,
        AccelPlan::Software,
        "report-only must not produce a hardware plan"
    );
    // But the *status* still knows what is out there, which is the point.
    let status = planner.status();
    if !status.available.is_empty() {
        assert!(
            status.unavailable.iter().all(|(_, r)| !r.is_empty()),
            "report-only status has an empty reason: {}",
            status.summary()
        );
    }
    // And the artifact still gets made.
    let out = dir.path().join("t.webp");
    let r = generator_with(plan).generate(&source, &out, Kind::Thumbnail { width: 120 }, &media);
    assert!(
        matches!(r, commons_media::thumbs::Generated::Wrote(_)),
        "{r:?}"
    );
}

/// A disabled accelerator produces a software plan even with the hardware
/// present, and the artifact is unchanged.
#[test]
fn a_disabled_accelerator_produces_the_same_bytes_as_no_accelerator() {
    let dir = tempfile::tempdir().unwrap();
    let source = make_video(dir.path(), 1);
    let media = info(1000);

    let none_out = dir.path().join("none.webp");
    generator_with(AccelPlan::Software).generate(
        &source,
        &none_out,
        Kind::Thumbnail { width: 120 },
        &media,
    );

    let config = HwAccelConfig {
        disabled: Accel::ALL.to_vec(),
        report_only: false,
    };
    let plan = Planner::detect(Path::new(&ffmpeg()), &config).plan_for_source(SourceKind::Video);
    assert_eq!(plan, AccelPlan::Software);

    let off_out = dir.path().join("off.webp");
    generator_with(plan).generate(&source, &off_out, Kind::Thumbnail { width: 120 }, &media);

    assert_eq!(
        std::fs::read(&none_out).unwrap(),
        std::fs::read(&off_out).unwrap(),
        "switching acceleration off changed the output bytes"
    );
}
