//! Word timestamps, against a hand-checked transcript.
//!
//! T-P6-004, spec §6 (the ticket's FIRST accept criterion): word timestamps
//! monotonic and within 200 ms of a hand-checked transcript.
//!
//! # Why the fixture is a .srt and the audio is generated
//!
//! The audio is synthesised by ffmpeg at test time — a tone, a silence, a tone,
//! at known durations — so the repository does not carry a binary every clone
//! must fetch, and so the *timing* is exact by construction rather than
//! approximate.
//!
//! The expected transcript is the opposite: it is checked in, because a
//! hand-checked thing cannot be generated by the thing it is checking. If the
//! engine produced its own expectations this test would assert that the engine
//! agrees with itself.
//!
//! # What can and cannot be asserted here
//!
//! With no ASR model on this machine, the test drives a `FakeEngine` that
//! reports words at known offsets. What that proves is the ARITHMETIC — the
//! absolute-timestamp contract, the chunk seam, the drop rules — which is where
//! every bug found in this ticket so far has been. It does not prove a model's
//! accuracy, and it is not written to look like it does.
//!
//! The model-backed half lives in `asr_model.rs` and is skipped when no model
//! is configured, loudly.

use std::path::{Path, PathBuf};

use commons_ml::asr::audio::{extract, Pcm16kMono, SAMPLE_RATE};
use commons_ml::asr::chunker::{run_chunks, Chunker, CHUNK_MS};
use commons_ml::asr::engine::{AsrError, TimedWord};
use commons_ml::asr::SpeakerId;

fn ffmpeg() -> String {
    std::env::var("COMMONS_FFMPEG").unwrap_or_else(|_| "ffmpeg".to_string())
}

/// Whether ffmpeg is actually there. A skip that prints is not a pass, so the
/// caller decides: the tests below PANIC rather than return early when this is
/// false, and the reason is on stderr.
fn ffmpeg_available() -> bool {
    std::process::Command::new(ffmpeg())
        .arg("-version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// A clip with speech-shaped energy: tone, silence, tone.
///
/// The silences matter. A window that is all silence is the one an ASR model
/// confabulates on, and a test clip with no silence in it would never exercise
/// the path where a fabricated word could enter the library.
fn make_clip(dir: &Path) -> PathBuf {
    let out = dir.join("interview.wav");
    // 3s tone, 1s silence, 3s tone, 2s silence, 4s tone = 13s, crossing the
    // 30s boundary is not possible at this length, so the seam is exercised by
    // a separate short-chunk test below.
    let filter = "sine=frequency=300:duration=3[s0];\
                  anullsrc=duration=1[s1];\
                  sine=frequency=300:duration=3[s2];\
                  anullsrc=duration=2[s3];\
                  sine=frequency=300:duration=4[s4];\
                  [s0][s1][s2][s3][s4]concat=n=5:v=0:a=1[out]";
    let status = std::process::Command::new(ffmpeg())
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            // `-filter_complex`, not `-f lavfi -i`: a multi-input graph with
            // its own labels is only a filter graph. Passing it as an input
            // silently builds nothing and ffmpeg then reports "Output with
            // label 'out' does not exist in any defined filter graph" --
            // which reads like a filter typo and is not one.
            "-filter_complex",
            filter,
            "-map",
            "[out]",
            "-ac",
            "1",
            "-ar",
            "16000",
            out.to_str().unwrap(),
        ])
        .status();
    assert!(
        status.map(|s| s.success()).unwrap_or(false),
        "ffmpeg could not build the fixture clip; set COMMONS_FFMPEG"
    );
    out
}

/// A fake engine that knows where its words are.
///
/// Deliberately NOT a trait impl: it takes the chunk so a test can vary its
/// output per window, which is how the seam and the failure tests work.
fn scripted<F>(
    mut f: F,
) -> impl FnMut(&commons_ml::asr::chunker::Chunk, &mut dyn FnMut(TimedWord)) -> Result<(), AsrError>
where
    F: FnMut(&commons_ml::asr::chunker::Chunk) -> Vec<TimedWord>,
{
    move |chunk, sink| {
        for w in f(chunk) {
            sink(w);
        }
        Ok(())
    }
}

fn word(
    text: &str,
    start: u32,
    end: u32,
    speaker: Option<SpeakerId>,
    score: Option<f32>,
) -> TimedWord {
    TimedWord {
        text: text.to_string(),
        start_ms: start,
        end_ms: end,
        confidence: score,
        speaker,
    }
}

fn tempdir(tag: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("commons-asr-{tag}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).expect("temp dir");
    d
}

#[test]
fn the_extracted_audio_is_the_length_the_filter_asked_for() {
    // The premise of every timing assertion below: the audio is 13 seconds
    // long, +/- one 20 ms frame, and the extraction really did resample.
    if !ffmpeg_available() {
        panic!("no ffmpeg: set COMMONS_FFMPEG");
    }
    let dir = tempdir("len");
    let clip = make_clip(&dir);
    let audio = extract(&clip).expect("extract");
    let ms = audio.duration_ms();
    assert!(
        (12_900..=13_100).contains(&ms),
        "expected ~13000ms of audio, got {ms}"
    );
    // 13s of 16kHz mono s16le is 416000 bytes, and the sample rate is not
    // negotiable: resampling inside the model instead would mean a second
    // resampler disagreeing with ffmpeg's, and the disagreement would show up
    // as exactly the timing drift this ticket forbids.
    assert_eq!(SAMPLE_RATE, 16_000);
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn a_word_at_the_chunk_seam_is_timed_from_the_media_not_the_window() {
    // The load-bearing assertion. A word 500 ms into the SECOND window is
    // 30.5s into the media. Getting this wrong by one window puts every chapter
    // after the first one in the wrong place, and the transcript itself still
    // reads perfectly.
    let audio = Pcm16kMono::from_bytes(vec![0u8; 16_000 * 2 * 70]);
    let got = run_chunks(
        &audio,
        &Chunker::default(),
        scripted(|chunk| {
            vec![word("seam", 500, 900, None, Some(0.9))]
                .into_iter()
                .map(|mut w| {
                    w.start_ms += 0; // relative to the window, by contract
                    let _ = chunk;
                    w
                })
                .collect()
        }),
    );
    assert!(got.is_monotonic());
    let last = got.words.last().expect("words");
    assert_eq!(last.start_ms, 60_000 + 500, "must be absolute");
    assert_eq!(last.end_ms, 60_000 + 900);
}

#[test]
fn words_stay_within_two_hundred_milliseconds_of_a_hand_checked_transcript() {
    // The ticket's criterion, stated as an assertion. The comparison is a
    // word-ALIGNMENT distance rather than a string compare, because the point
    // is timing accuracy and a string compare conflates it with wording
    // differences between model versions.
    //
    // The reference here is the SRT the human checked, parsed below; the
    // tolerance is the 200 ms the ticket names.
    const TOLERANCE_MS: i64 = 200;

    let expected = parse_srt(include_str!("fixtures/hand-checked.srt"));
    assert!(!expected.is_empty(), "the fixture must not be empty");

    // The scripted engine reproduces those timings exactly, so the measured
    // distance is 0 and the assertion is about the ARITHMETIC carrying them
    // through four windows unchanged.
    let audio = Pcm16kMono::from_bytes(vec![0u8; 16_000 * 2 * 90]);
    let got = run_chunks(
        &audio,
        &Chunker::default(),
        scripted(|chunk| {
            expected
                .iter()
                .filter(|(s, _, _)| *s >= chunk.start_ms as u32 && *s < chunk.end_ms as u32)
                .map(|(s, e, text)| {
                    word(
                        text,
                        *s - chunk.start_ms as u32,
                        *e - chunk.start_ms as u32,
                        None,
                        Some(0.95),
                    )
                })
                .collect()
        }),
    );

    assert_eq!(got.words.len(), expected.len(), "no word may be lost");
    for (i, (want_start, _, want_text)) in expected.iter().enumerate() {
        let have = &got.words[i];
        let drift = (have.start_ms as i64 - *want_start as i64).abs();
        assert!(
            drift <= TOLERANCE_MS,
            "word {i} ({want_text:?}) drifted {drift}ms from {}ms",
            want_start
        );
    }
    assert!(got.is_monotonic(), "timestamps must be non-decreasing");
    assert!(got.all_intervals_sane());
    assert_eq!(got.dropped, 0, "no word should be dropped");
}

/// Parse the checked fixture into `(start_ms, end_ms, text)`.
///
/// Parsed in the test rather than imported from the subtitle module, because
/// that module's SRT reader is for *subtitles* and applies its own
/// normalisation (it strips styling and offsets a second track by its index),
/// neither of which is wanted for a reference transcript.
fn parse_srt(src: &str) -> Vec<(u32, u32, String)> {
    let mut out = Vec::new();
    let mut lines = src.lines().peekable();
    while let Some(line) = lines.next() {
        let line = line.trim();
        if line.is_empty() || line.chars().all(|c| c.is_ascii_digit()) {
            continue; // blank, or the cue number
        }
        let (start, end) = line.split_once(" --> ").expect("a timing line");
        let text = lines.next().unwrap_or_default().trim().to_string();
        out.push((parse_ts(start), parse_ts(end), text));
    }
    out
}

fn parse_ts(s: &str) -> u32 {
    let mut parts = s.trim().split(':');
    let h: u32 = parts.next().unwrap().parse().expect("hours");
    let m: u32 = parts.next().expect("minutes").parse().expect("minutes");
    let rest = parts.next().expect("seconds");
    let (sec, millis) = match rest.split_once(',') {
        Some((s, ms)) => (s, ms),
        // SRT writes `.` for the decimal point in some producers; a timestamp
        // without a fraction is still a valid cue.
        None => (rest, "0"),
    };
    let sec: u32 = sec.parse().expect("seconds");
    let millis: u32 = millis.parse().expect("millis");
    (h * 3600 + m * 60 + sec) * 1000 + millis
}

#[test]
fn a_window_of_silence_produces_no_words_and_is_not_an_error() {
    // An ASR model handed near-silence confabulates, and that confabulation
    // goes into the library as though a person said it. The engine here reports
    // nothing for a silent window and the run must not treat that as a failure.
    let audio = Pcm16kMono::from_bytes(vec![0u8; 16_000 * 2 * 90]);
    let got = run_chunks(&audio, &Chunker::default(), scripted(|_| Vec::new()));
    assert!(got.words.is_empty());
    assert_eq!(got.dropped, 0, "an empty window is not a dropped word");
}

#[test]
fn a_tiny_window_is_never_handed_to_an_engine() {
    // The last window of a 30s + 0.2s clip is 200ms, below MIN_AUDIO_MS.
    let audio = Pcm16kMono::from_bytes(vec![0u8; 16_000 * 2 * 30 + 320]);
    let windows = Chunker::default().windows(&audio);
    let last = windows.last().unwrap();
    assert!(last.duration_ms() < CHUNK_MS);
    assert!(
        !last.is_worth_transcribing(),
        "a {last:?} window must be skipped"
    );
}

#[test]
fn a_speaker_id_survives_the_round_trip_into_absolute_time() {
    // Speaker attribution is per-transcript and lands in a cluster by
    // PROPOSAL, so the id has to survive the arithmetic intact.
    let audio = Pcm16kMono::from_bytes(vec![0u8; 16_000 * 2 * 60]);
    let got = run_chunks(
        &audio,
        &Chunker::default(),
        scripted(|chunk| {
            vec![word(
                "hello",
                100,
                400,
                Some(SpeakerId((chunk.index % 2) as u16)),
                None,
            )]
        }),
    );
    assert!(got.words.iter().all(|w| w.speaker.is_some()));
    assert_eq!(got.words[0].speaker, Some(SpeakerId(0)));
    assert_eq!(got.words[1].speaker, Some(SpeakerId(1)));
}

#[test]
fn a_non_scoring_engine_produces_null_confidence_not_zero() {
    let audio = Pcm16kMono::from_bytes(vec![0u8; 16_000 * 2 * 30]);
    let got = run_chunks(
        &audio,
        &Chunker::default(),
        scripted(|_| vec![word("x", 0, 100, None, None)]),
    );
    assert_eq!(got.words[0].confidence, None);
}
