[package]
name = "commons-ml"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
commons-core = { workspace = true }
commons-store = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
parking_lot = { workspace = true }
camino = { workspace = true }
tokio = { workspace = true }
usearch = { workspace = true }

[dev-dependencies]
commons-store = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
