#!/usr/bin/env python3
"""Emit the theme CSS custom properties from the TypeScript token source.

T-P5-007. The tokens live in `ui/src/lib/theme/contrast.ts` because that is
where the WCAG arithmetic and the pair list live, and the pair list is the
thing that has to be checked. The CSS needs the same values.

**Why a generator rather than a hand-written `:root` block.**

Two hand-maintained copies of a colour set drift. They drift *quietly*: the CSS
is what a user sees and the TS is what the tests check, so a token edited in
one place produces a suite that is green and a page that fails contrast. The
contrast test cannot catch that, because it tests the TS.

So the CSS is generated, `--check` fails when it is out of date, and
`verify.sh` runs that. Editing a colour is now: edit the TS, run this.

**Why the tokens are read with a regex and not a JS runtime.** The file is
TypeScript with no runtime here, and a regex over `readonly name: 'dark',` plus
its siblings is enough -- the file is a flat object literal and the test
already fails loudly if it stops being one.

Run:  python3 scripts/gen-theme-css.py [--check]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "ui" / "src" / "lib" / "theme" / "contrast.ts"
DST = REPO / "ui" / "src" / "theme.css"

# The token order is fixed here rather than derived, because a generated file
# whose order follows a hash is unreviewable in a diff.
ORDER = [
    "bg",
    "surface",
    "fg",
    "muted",
    "border",
    "focus",
    "accent",
    "onAccent",
    "danger",
]


def read_themes(text: str) -> dict[str, dict[str, str]]:
    """Pull `name: 'x', token: 'hex',` pairs out of each theme literal."""
    out: dict[str, dict[str, str]] = {}
    # Split on the two exported literals. A theme that stopped being a flat
    # literal makes this return nothing, and the caller reports the file.
    for m in re.finditer(
        r"export const (DARK|LIGHT): ThemeTokens = \{(.*?)\n\};", text, re.S
    ):
        name = m.group(1).lower()
        body = m.group(2)
        vals = dict(re.findall(r"(\w+):\s*'([0-9a-fA-F]{6})'", body))
        out[name] = vals
    return out


def render(themes: dict[str, dict[str, str]]) -> str:
    if "dark" not in themes or "light" not in themes:
        raise SystemExit(f"{SRC}: expected a DARK and a LIGHT literal")

    missing = [
        f"{name}.{tok}"
        for name, vals in themes.items()
        for tok in ORDER
        if tok not in vals
    ]
    if missing:
        raise SystemExit(f"{SRC}: no value for {', '.join(missing)}")

    lines = [
        "/* GENERATED by scripts/gen-theme-css.py from",
        " * ui/src/lib/theme/contrast.ts. Do not edit by hand.",
        " *",
        " * The colours are here because the contrast arithmetic is there, and the",
        " * pair list in that file is the contract the tests check. A hand-",
        " * written copy of these values would drift from the checked ones and",
        " * the drift is invisible: the test would still be green.",
        " *",
        " * Every pair below clears its WCAG threshold in its own theme. The",
        " * numbers are asserted in ui/tests/contrast.test.ts, not asserted",
        " * here -- this file is a rendering of them, not a second opinion. */",
        "",
        ':root,',
        '[data-theme="dark"] {',
    ]
    for tok in ORDER:
        lines.append(f"  --{kebab(tok)}: #{themes['dark'][tok]};")
    lines += [
        "  color-scheme: dark;",
        "}",
        "",
        '[data-theme="light"] {',
    ]
    for tok in ORDER:
        lines.append(f"  --{kebab(tok)}: #{themes['light'][tok]};")
    lines += [
        "  color-scheme: light;",
        "}",
        "",
    ]
    return "\n".join(lines)


def read_decls(text: str) -> dict[tuple[str, str], str]:
    """Every `--tok: #hex` in the file, keyed by (theme, token)."""
    out: dict[tuple[str, str], str] = {}
    theme = "?"
    for line in text.splitlines():
        t = line.strip()
        if t.startswith('[data-theme='):
            theme = t.split('"')[1] if '"' in t else "root"
        m = re.match(r"--([a-z-]+):\s*(#[0-9a-f]{6});", t)
        if m:
            out[(theme, m.group(1))] = m.group(2)
    return out


def kebab(tok: str) -> str:
    """`onAccent` -> `on-accent`, which is the CSS spelling."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", tok).lower()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if out of date")
    args = ap.parse_args()

    want = render(read_themes(SRC.read_text()))
    if args.check:
        if not DST.exists():
            print(f"FAIL: {DST} does not exist. Run: python3 scripts/gen-theme-css.py")
            return 1
        have = DST.read_text()
        if have != want:
            print(f"FAIL: {DST} is out of date with {SRC.name}.")
            print("      Run: python3 scripts/gen-theme-css.py")
            # Say WHICH token, so this is a two-second fix rather than a diff
            # read. A generator that reports "regenerate" and nothing else
            # costs the same time as the check saved.
            #
            # The key is (theme, token), NOT token. Both themes declare the
            # same nine names, so keying on the name alone keeps only the LAST
            # block -- which is the light theme -- and a drift in the dark
            # theme reports as no drift at all. The first version of this
            # diagnostic had that bug, and it is the same shape as the two
            # hand-maintained copies this generator exists to prevent.
            have_t = read_decls(have)
            want_t = read_decls(want)
            for k in sorted(set(have_t) | set(want_t)):
                if have_t.get(k) != want_t.get(k):
                    theme, tok = k
                    print(f"      [{theme}] --{tok}: on disk {have_t.get(k)}, source {want_t.get(k)}")
            return 1
        print(f"ok: {DST.name} matches {SRC.name}")
        return 0

    DST.write_text(want)
    print(f"wrote {DST.relative_to(REPO)} ({len(want.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
